### ISSUE TITLE
Custom BLBAUD for frser-duino

### ISSUE THREAD

**Issue by bovcan** [urjaman/fast-usbserial#3]
Hi.
I have updated fw on arduino's 16u2 chip and than I made
make ftdi
make flash-u2
 Than with command:
e.g flashrom -o test.txt -p serprog:dev=com4:2000000 -r test.bin
I got errors flashrom  invalid response 0xFF from device and something about a buffer.

can this speed be custom adjusted?

**Comment by urjaman** [comment]
This is not a fast-usbserial issue, atleast directly - it will do any baudrate the OS requests.
You will need flashrom 0.9.9 to support high baud rates on windows (this i think is your most likely problem, check it first).
I'll note that I havent tested fast-usbserial on a windows host, so YMMV.

The following is about frser-duino, but i'll put it here anyways...
BLBAUD would mean bootloader baudrate which i dont think you want to change unless you changed the bootloader on the m328, but FRBAUD which is the speed used to communicate with flashrom.
Those are set in the frser-duino Makefile: 
https://github.com/urjaman/frser-duino/blob/master/Makefile#L94 
You could try 500000 (0.5M) and then 1000000 (1M) just to see if your host is in some way derp and unable to keep up with the full 2M.
